# Generated by Django 4.2.7 on 2026-03-27 11:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('staff', 'Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'permissions': [('course:view', 'Can view courses'), ('course:create', 'Can create courses'), ('course:edit', 'Can edit courses'), ('course:delete', 'Can delete courses'), ('course:enroll', 'Can enroll in courses'), ('course:manage', 'Can manage courses'), ('assignment:view', 'Can view assignments'), ('assignment:create', 'Can create assignments'), ('assignment:edit', 'Can edit assignments'), ('assignment:delete', 'Can delete assignments'), ('assignment:submit', 'Can submit assignments'), ('assignment:grade', 'Can grade assignments'), ('grade:view', 'Can view grades'), ('grade:edit', 'Can edit grades'), ('grade:manage', 'Can manage grades'), ('schedule:view', 'Can view schedule'), ('schedule:create', 'Can create schedule'), ('schedule:edit', 'Can edit schedule'), ('schedule:delete', 'Can delete schedule'), ('schedule:manage', 'Can manage schedule'), ('schedule:book', 'Can book appointments'), ('schedule:attend', 'Can mark attendance'), ('fees:view', 'Can view fees'), ('fees:create', 'Can create fees'), ('fees:edit', 'Can edit fees'), ('fees:delete', 'Can delete fees'), ('fees:manage', 'Can manage fees'), ('fees:pay', 'Can pay fees'), ('fees:refund', 'Can refund fees'), ('fees:report', 'Can generate fee reports'), ('fees:structure:view', 'Can view fee structure'), ('fees:structure:edit', 'Can edit fee structure'), ('fees:discount:apply', 'Can apply discounts'), ('fees:dues:track', 'Can track dues'), ('staff:view', 'Can view staff'), ('staff:create', 'Can create staff'), ('staff:edit', 'Can edit staff'), ('staff:delete', 'Can delete staff'), ('staff:manage', 'Can manage staff'), ('staff:schedule:view', 'Can view staff schedule'), ('staff:schedule:edit', 'Can edit staff schedule'), ('staff:performance:view', 'Can view staff performance'), ('staff:performance:edit', 'Can edit staff performance'), ('staff:leave:view', 'Can view staff leave'), ('staff:leave:approve', 'Can approve staff leave'), ('staff:leave:request', 'Can request leave'), ('staff:documents:view', 'Can view staff documents'), ('staff:documents:upload', 'Can upload staff documents'), ('parent:view', 'Can view parents'), ('parent:create', 'Can create parents'), ('parent:edit', 'Can edit parents'), ('parent:delete', 'Can delete parents'), ('parent:manage', 'Can manage parents'), ('parent:communicate', 'Can communicate with parents'), ('parent:meeting:schedule', 'Can schedule parent meetings'), ('parent:progress:view', 'Can view parent progress reports'), ('parent:fees:view', 'Can view parent fees'), ('parent:fees:pay', 'Can pay parent fees'), ('parent:attendance:view', 'Can view parent attendance'), ('student:view', 'Can view students'), ('student:create', 'Can create students'), ('student:edit', 'Can edit students'), ('student:delete', 'Can delete students'), ('student:manage', 'Can manage students'), ('student:enroll', 'Can enroll students'), ('student:withdraw', 'Can withdraw students'), ('student:attendance:view', 'Can view student attendance'), ('student:attendance:mark', 'Can mark student attendance'), ('student:progress:view', 'Can view student progress'), ('student:progress:edit', 'Can edit student progress'), ('student:behavior:view', 'Can view student behavior'), ('student:behavior:report', 'Can report student behavior'), ('student:documents:view', 'Can view student documents'), ('student:documents:upload', 'Can upload student documents'), ('student:transcript:view', 'Can view student transcript'), ('student:transcript:generate', 'Can generate student transcript'), ('teacher:view', 'Can view teachers'), ('teacher:create', 'Can create teachers'), ('teacher:edit', 'Can edit teachers'), ('teacher:delete', 'Can delete teachers'), ('teacher:manage', 'Can manage teachers'), ('teacher:schedule:view', 'Can view teacher schedule'), ('teacher:schedule:edit', 'Can edit teacher schedule'), ('teacher:performance:view', 'Can view teacher performance'), ('teacher:performance:edit', 'Can edit teacher performance'), ('teacher:leave:view', 'Can view teacher leave'), ('teacher:leave:approve', 'Can approve teacher leave'), ('teacher:leave:request', 'Can request leave'), ('teacher:courses:assign', 'Can assign courses to teachers'), ('teacher:evaluation:view', 'Can view teacher evaluations'), ('teacher:evaluation:submit', 'Can submit teacher evaluations'), ('user:view', 'Can view users'), ('user:create', 'Can create users'), ('user:edit', 'Can edit users'), ('user:delete', 'Can delete users'), ('user:manage', 'Can manage users'), ('settings:view', 'Can view settings'), ('settings:edit', 'Can edit settings'), ('reports:view', 'Can view reports'), ('reports:generate', 'Can generate reports'), ('dashboard:view', 'Can view dashboard'), ('dashboard:customize', 'Can customize dashboard')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('level_number', models.IntegerField(unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('min_age', models.IntegerField(default=7)),
                ('max_age', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'grade_levels',
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
            ],
            options={
                'db_table': 'staff',
                'permissions': [('can_view_staff_performance', 'Can view staff performance'), ('can_edit_staff_performance', 'Can edit staff performance'), ('can_manage_staff_schedule', 'Can manage staff schedule'), ('can_approve_staff_leave', 'Can approve staff leave')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('enrollment_date', models.DateField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('performance', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs-improvement', 'Needs Improvement'), ('at-risk', 'At Risk')], default='average', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('pending', 'Pending Enrollment')], default='pending', max_length=20)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('has_allergies', models.BooleanField(default=False)),
                ('allergy_details', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
                'permissions': [('can_view_student_progress', 'Can view student progress'), ('can_edit_student_progress', 'Can edit student progress'), ('can_mark_attendance', 'Can mark attendance'), ('can_view_attendance', 'Can view attendance'), ('can_report_behavior', 'Can report behavior'), ('can_view_behavior', 'Can view behavior'), ('can_manage_student_documents', 'Can manage student documents'), ('can_view_student_documents', 'Can view student documents'), ('can_enroll_students', 'Can enroll students'), ('can_withdraw_students', 'Can withdraw students')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
            ],
            options={
                'db_table': 'teachers',
                'permissions': [('can_view_teacher_performance', 'Can view teacher performance'), ('can_edit_teacher_performance', 'Can edit teacher performance'), ('can_manage_teacher_schedule', 'Can manage teacher schedule'), ('can_approve_teacher_leave', 'Can approve teacher leave')],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='accounts.student')),
            ],
            options={
                'db_table': 'student_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('health_record', 'Health Record'), ('previous_school', 'Previous School Records'), ('identification', 'Identification'), ('medical', 'Medical Information'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='student_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.student')),
            ],
            options={
                'db_table': 'student_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisees', to='accounts.teacher'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='accounts.student')),
            ],
            options={
                'db_table': 'parents',
                'permissions': [('can_view_parent_details', 'Can view parent details'), ('can_edit_parent_details', 'Can edit parent details'), ('can_communicate_with_parents', 'Can communicate with parents'), ('can_schedule_parent_meetings', 'Can schedule parent meetings')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'role'], name='users_email_7645ab_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_student_1ff8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_status_3ac771_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['performance'], name='students_perform_d08a35_idx'),
        ),
    ]
