# Generated by Django 4.2.7 on 2026-04-18 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('access_level', models.CharField(choices=[('super', 'Super Admin'), ('system', 'System Admin'), ('academic', 'Academic Admin'), ('finance', 'Finance Admin'), ('staff', 'Staff Admin')], default='system', max_length=20)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admins',
                'permissions': [('can_manage_system', 'Can manage system settings'), ('can_manage_users', 'Can manage all users'), ('can_view_audit_logs', 'Can view audit logs'), ('can_manage_permissions', 'Can manage permissions')],
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('quran', 'Qur’an Memorization (Hifz)'), ('tajweed', 'Tajweed'), ('islamic_studies', 'Islamic Studies'), ('fiqh', 'Fiqh'), ('aqeedah', 'Aqeedah'), ('english', 'English'), ('mathematics', 'Mathematics'), ('science', 'Science'), ('social_studies', 'Social Studies'), ('administration', 'Administration'), ('boarding', 'Boarding / Student Affairs')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, choices=[('ustadh', 'Ustadh (Teacher)'), ('ustadha', 'Ustadha (Female Teacher)'), ('senior_teacher', 'Senior Teacher'), ('head_of_department', 'Head of Department'), ('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('boarding_master', 'Boarding Master'), ('boarding_mistress', 'Boarding Mistress')], max_length=50, null=True),
        ),
    ]
