# Generated by Django 4.2.7 on 2026-03-27 11:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('credits', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('max_students', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_students', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('archived', 'Archived'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='accounts.gradelevel')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to='accounts.teacher')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('term_type', models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear')),
            ],
            options={
                'db_table': 'terms',
                'ordering': ['start_date'],
                'unique_together': {('academic_year', 'term_type')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('quran', 'Quran'), ('tajweed', 'Tajweed'), ('tahfiz', 'Tahfiz (Memorization)'), ('arabic', 'Arabic Language'), ('islamic_history', 'Islamic History'), ('aqeedah', 'Aqeedah'), ('fiqh', 'Fiqh'), ('seerah', 'Seerah'), ('adab', 'Adab (Islamic Ethics)'), ('mathematics', 'Mathematics'), ('english', 'English Language'), ('science', 'Science'), ('social_studies', 'Social Studies'), ('malay', 'Malay Language'), ('physical_education', 'Physical Education'), ('arts', 'Arts'), ('ict', 'Information Technology')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_islamic', models.BooleanField(default=False)),
                ('requires_memorization', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='subjects_categor_8c1690_idx'), models.Index(fields=['is_islamic'], name='subjects_is_isla_da8631_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('ppt', 'Presentation'), ('video', 'Video'), ('link', 'Link'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/%Y/%m/')),
                ('url', models.URLField(blank=True)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academics.course')),
            ],
            options={
                'db_table': 'course_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.term'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('pending', 'Pending'), ('waitlisted', 'Waitlisted'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='enrolled', max_length=20)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=5)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student')),
            ],
            options={
                'db_table': 'enrollments',
                'indexes': [models.Index(fields=['student', 'status'], name='enrollments_student_929bef_idx'), models.Index(fields=['course', 'status'], name='enrollments_course__931283_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_code_fa42f1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_status_67f368_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['grade_level'], name='courses_grade_l_dc768e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject'], name='courses_subject_f2143c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='courses_instruc_77fba4_idx'),
        ),
    ]
