# Generated by Django 4.2.7 on 2026-04-18 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_admin_teacher_department_teacher_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_choice', models.JSONField(blank=True, default=list)),
                ('file_attachments', models.JSONField(blank=True, default=list)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam'), ('assignment', 'Assignment'), ('project', 'Project'), ('participation', 'Participation'), ('homework', 'Homework')], max_length=20)),
                ('total_points', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weight towards final grade', max_digits=5)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('attempts_allowed', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('late_submission_days', models.IntegerField(default=0)),
                ('late_penalty_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('auto_grade', models.BooleanField(default=False, help_text='Whether assessment can be auto-graded')),
                ('rubric_id', models.UUIDField(blank=True, help_text='Reference to rubric if used', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('closed', 'Closed'), ('grading', 'Grading'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('show_answers_after_due', models.BooleanField(default=False)),
                ('show_scores_immediately', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('holiday', 'Holiday')], max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('letter_grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F'), ('I', 'Incomplete'), ('W', 'Withdrawn')], max_length=2)),
                ('gpa_points', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('quiz_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('project_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('participation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=2)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa_points', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grade_scales',
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('matching', 'Matching'), ('fill_blank', 'Fill in the Blank'), ('file_upload', 'File Upload')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for multiple choice')),
                ('correct_answer', models.JSONField(blank=True, default=list, help_text='Correct answer(s)')),
                ('sample_answer', models.TextField(blank=True, help_text='Sample answer for grading reference')),
                ('max_words', models.IntegerField(blank=True, null=True)),
                ('allowed_file_types', models.JSONField(blank=True, default=list, help_text='List of allowed file extensions')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for correct answer')),
                ('hint', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers_data', models.JSONField(default=dict, help_text='Structured answers for each question')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Uploaded files')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('attempt_number', models.IntegerField(default=1)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded'), ('returned', 'Returned')], default='in_progress', max_length=20)),
                ('auto_grade_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'mp4', 'zip'])]),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['academic_year', 'term'], name='courses_academi_481ada_idx'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assessment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.assessment'),
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('name', 'grade')},
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academics.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_items', to='academics.submission'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assessment', 'student'], name='submissions_assessm_434ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_dcc854_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='submissions_submitt_9b96b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assessment', 'student', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assessment', 'type'], name='questions_assessm_8d2738_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'letter_grade'], name='grades_student_78c019_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['course', 'letter_grade'], name='grades_course__a5eb1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attendances_student_1e9785_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['course', 'date'], name='attendances_course__7b33fa_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendances_date_234e8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course', 'date')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['course', 'type'], name='assessments_course__e054fd_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status'], name='assessments_status_621393_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['due_date'], name='assessments_due_dat_796263_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['course', 'due_date'], name='assessments_course__53185e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('submission', 'question')},
        ),
    ]
