# Generated by Django 4.2.7 on 2026-04-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='children',
        ),
        migrations.CreateModel(
            name='ApplicantParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_parent', to='applications.application')),
            ],
            options={
                'verbose_name': 'Applicant Parent',
                'verbose_name_plural': 'Applicant Parents',
                'db_table': 'applicant_parents',
            },
        ),
        migrations.CreateModel(
            name='ApplicantChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('has_allergies', models.BooleanField(default=False)),
                ('allergy_details', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_children', to='applications.application')),
            ],
            options={
                'verbose_name': 'Applicant Child',
                'verbose_name_plural': 'Applicant Children',
                'db_table': 'applicant_children',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
