# Generated by Django 4.2.7 on 2026-04-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_children_applicantparent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='privacy_accepted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='terms_accepted',
        ),
    ]
